
'''
FastAPI serving app for the Hospital Readmission Risk Predictor.

Generated by 05_MLflow_Registry_FastAPI.ipynb -- do not hand-edit the
FEATURE_COLUMNS list below; re-run that notebook's Section 9 instead so it
stays in sync with whatever model is currently registered.

Run locally with:
    uvicorn serve.main:app --reload --port 8000
'''
import pandas as pd
from typing import Any, Dict, Optional

import mlflow
import mlflow.sklearn
from mlflow.tracking import MlflowClient
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel

MLFLOW_TRACKING_URI = (
    "sqlite:///C:/Users/angie/Documents/GitHub/"
    "hospital-readmission-risk-predictor/"
    "AngelineSetiawan-hospital-readmission-risk-predictor/"
    "mlflow.db"
)

MODEL_NAME = 'hospital-readmission-risk-classifier'
FEATURE_COLUMNS = ['race', 'gender', 'age', 'admission_type_id', 'admission_source_id', 'time_in_hospital', 'payer_code', 'medical_specialty', 'num_lab_procedures', 'num_procedures', 'num_medications', 'number_outpatient', 'number_emergency', 'number_inpatient', 'number_diagnoses', 'max_glu_serum', 'A1Cresult', 'metformin', 'repaglinide', 'nateglinide', 'chlorpropamide', 'glimepiride', 'acetohexamide', 'glipizide', 'glyburide', 'tolbutamide', 'pioglitazone', 'rosiglitazone', 'acarbose', 'miglitol', 'troglitazone', 'tolazamide', 'examide', 'citoglipton', 'insulin', 'glyburide-metformin', 'glipizide-metformin', 'glimepiride-pioglitazone', 'metformin-rosiglitazone', 'metformin-pioglitazone', 'change', 'diabetesMed', 'admission_type_id_label', 'admission_source_id_label', 'max_glu_serum_tested', 'A1Cresult_tested', 'diag_1_group', 'diag_2_group', 'diag_3_group']

mlflow.set_tracking_uri(MLFLOW_TRACKING_URI)

app = FastAPI(
    title="Hospital Readmission Risk Predictor",
    description="Serves 30-day readmission risk scores from whichever model "
                "version is currently tagged Production in the MLflow registry.",
)

# Populated on startup by _load_production_model(); kept as simple module-level
# state so every request reuses the same loaded model instead of re-loading it.
_state: Dict[str, Any] = {"model": None, "threshold": None, "version": None, "run_id": None}


# def _get_production_version(client: MlflowClient):
#     '''Return the highest-numbered model version tagged stage=Production.'''
#     candidates = [
#         mv for mv in client.search_model_versions(f"name='{MODEL_NAME}'")
#         if mv.tags.get("stage") == "Production"
#     ]
#     if not candidates:
#         raise RuntimeError(f"No version of '{MODEL_NAME}' is tagged stage=Production.")
#     return max(candidates, key=lambda mv: int(mv.version))

def _get_production_version(client: MlflowClient):
    """Return the highest-numbered model version in the Production stage."""
    candidates = [
        mv
        for mv in client.search_model_versions(f"name='{MODEL_NAME}'")
        if mv.current_stage == "Production"
    ]

    if not candidates:
        raise RuntimeError(
            f"No version of '{MODEL_NAME}' is in the Production stage."
        )

    return max(candidates, key=lambda mv: int(mv.version))


def _load_production_model():
    '''Load the current Production model and its tuned threshold, and cache both.'''
    client = MlflowClient()
    version = _get_production_version(client)
    model = mlflow.sklearn.load_model(f"models:/{MODEL_NAME}/{version.version}")

    # The threshold that was tuned specifically for this model version is
    # read from its own run, not hardcoded, so a future model version with
    # a different tuned threshold is served correctly with no code change.
    run = client.get_run(version.run_id)
    threshold = float(run.data.params["selected_threshold"])

    _state["model"] = model
    _state["threshold"] = threshold
    _state["version"] = version.version
    _state["run_id"] = version.run_id


@app.on_event("startup")
def startup_event():
    _load_production_model()


class PredictionRequest(BaseModel):
    '''One patient encounter. Keys should match the modeling feature names;
    missing keys are imputed by the model's own preprocessing pipeline,
    the same way missing values are handled during training.'''
    features: Dict[str, Any]


class PredictionResponse(BaseModel):
    readmission_probability: float
    predicted_high_risk: bool
    threshold_used: float
    model_version: str
    run_id: str


@app.get("/health")
def health():
    if _state["model"] is None:
        raise HTTPException(status_code=503, detail="Model not loaded.")
    return {
        "status": "ok",
        "model_name": MODEL_NAME,
        "model_version": _state["version"],
        "run_id": _state["run_id"],
        "threshold": _state["threshold"],
    }


@app.post("/predict", response_model=PredictionResponse)
def predict(request: PredictionRequest):
    if _state["model"] is None:
        raise HTTPException(status_code=503, detail="Model not loaded.")

    # Build a one-row DataFrame reindexed to the exact training column order.
    # Any feature not supplied in the request becomes NaN, which the
    # pipeline's SimpleImputer steps handle the same way they do at training time.
    row = pd.DataFrame([request.features]).reindex(columns=FEATURE_COLUMNS)

    probability = float(_state["model"].predict_proba(row)[:, 1][0])
    threshold = _state["threshold"]

    return PredictionResponse(
        readmission_probability=probability,
        predicted_high_risk=probability >= threshold,
        threshold_used=threshold,
        model_version=str(_state["version"]),
        run_id=_state["run_id"],
    )


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
